// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: protobuf.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServerStreamingRPC_Test_FullMethodName = "/gprc.ServerStreamingRPC/Test"
)

// ServerStreamingRPCClient is the client API for ServerStreamingRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerStreamingRPCClient interface {
	Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (ServerStreamingRPC_TestClient, error)
}

type serverStreamingRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStreamingRPCClient(cc grpc.ClientConnInterface) ServerStreamingRPCClient {
	return &serverStreamingRPCClient{cc}
}

func (c *serverStreamingRPCClient) Test(ctx context.Context, in *Request, opts ...grpc.CallOption) (ServerStreamingRPC_TestClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerStreamingRPC_ServiceDesc.Streams[0], ServerStreamingRPC_Test_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStreamingRPCTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerStreamingRPC_TestClient interface {
	Recv() (*Reply, error)
	grpc.ClientStream
}

type serverStreamingRPCTestClient struct {
	grpc.ClientStream
}

func (x *serverStreamingRPCTestClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerStreamingRPCServer is the server API for ServerStreamingRPC service.
// All implementations must embed UnimplementedServerStreamingRPCServer
// for forward compatibility
type ServerStreamingRPCServer interface {
	Test(*Request, ServerStreamingRPC_TestServer) error
	mustEmbedUnimplementedServerStreamingRPCServer()
}

// UnimplementedServerStreamingRPCServer must be embedded to have forward compatible implementations.
type UnimplementedServerStreamingRPCServer struct {
}

func (UnimplementedServerStreamingRPCServer) Test(*Request, ServerStreamingRPC_TestServer) error {
	return status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedServerStreamingRPCServer) mustEmbedUnimplementedServerStreamingRPCServer() {}

// UnsafeServerStreamingRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerStreamingRPCServer will
// result in compilation errors.
type UnsafeServerStreamingRPCServer interface {
	mustEmbedUnimplementedServerStreamingRPCServer()
}

func RegisterServerStreamingRPCServer(s grpc.ServiceRegistrar, srv ServerStreamingRPCServer) {
	s.RegisterService(&ServerStreamingRPC_ServiceDesc, srv)
}

func _ServerStreamingRPC_Test_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerStreamingRPCServer).Test(m, &serverStreamingRPCTestServer{stream})
}

type ServerStreamingRPC_TestServer interface {
	Send(*Reply) error
	grpc.ServerStream
}

type serverStreamingRPCTestServer struct {
	grpc.ServerStream
}

func (x *serverStreamingRPCTestServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

// ServerStreamingRPC_ServiceDesc is the grpc.ServiceDesc for ServerStreamingRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerStreamingRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gprc.ServerStreamingRPC",
	HandlerType: (*ServerStreamingRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Test",
			Handler:       _ServerStreamingRPC_Test_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf.proto",
}
